/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.company.GerenciarContatos;

public final class R {
    public static final class attr {
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int editable=0x7f010001;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int max=0x7f010003;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int min=0x7f010002;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int visible=0x7f010000;
    }
    public static final class color {
        public static final int background_gray=0x7f080001;
        public static final int seperator=0x7f080000;
    }
    public static final class dimen {
        public static final int border=0x7f090001;
        public static final int seperator=0x7f090000;
        public static final int ssl_header_space=0x7f090002;
    }
    public static final class drawable {
        public static final int adfmf_icon=0x7f020000;
        public static final int adfmf_loading=0x7f020001;
        public static final int back_btn_disabled_control=0x7f020002;
        public static final int back_btn_normal_control=0x7f020003;
        public static final int back_btn_pressed_control=0x7f020004;
        public static final int bg_leather_repeatable=0x7f020005;
        public static final int bg_more_titlebar_repeatable=0x7f020006;
        public static final int btn_back=0x7f020007;
        public static final int btn_forward=0x7f020008;
        public static final int btn_refresh=0x7f020009;
        public static final int button_round_corner=0x7f02000a;
        public static final int ic_delete=0x7f02000b;
        public static final int ic_dialog_alert=0x7f02000c;
        public static final int ic_menu_hide_navbar=0x7f02000d;
        public static final int ic_menu_preferences=0x7f02000e;
        public static final int ic_menu_rearrange=0x7f02000f;
        public static final int ic_menu_show_navbar=0x7f020010;
        public static final int ic_menu_springboard=0x7f020011;
        public static final int ic_more_drag_unselected=0x7f020012;
        public static final int ic_tab_more_selected=0x7f020013;
        public static final int ic_tab_more_unselected=0x7f020014;
        public static final int indicator_input_error=0x7f020015;
        public static final int more_action_panel_background=0x7f020016;
        public static final int more_tab_selector=0x7f020017;
        public static final int more_titlebar_background=0x7f020018;
        public static final int next_btn_disabled_control=0x7f020019;
        public static final int next_btn_normal_control=0x7f02001a;
        public static final int next_btn_pressed_control=0x7f02001b;
        public static final int reload_btn_normal_control=0x7f02001c;
        public static final int reload_btn_pressed_control=0x7f02001d;
        public static final int text_round_corner=0x7f02001e;
    }
    public static final class id {
        public static final int action_panel=0x7f050011;
        public static final int addInfo=0x7f05003c;
        public static final int adfmf_blank_activity_text=0x7f05000b;
        public static final int adfmf_log_text=0x7f05000c;
        public static final int adfmf_login_button=0x7f05000d;
        public static final int btn_cancel=0x7f050013;
        public static final int btn_continue=0x7f050049;
        public static final int btn_done=0x7f050012;
        public static final int btn_view_certificate=0x7f05004a;
        public static final int buttonLyt=0x7f050019;
        public static final int cacancel=0x7f050042;
        public static final int cahead=0x7f05003f;
        public static final int cancel=0x7f05001b;
        public static final int cans=0x7f050040;
        public static final int casubmit=0x7f050041;
        public static final int connect=0x7f050000;
        public static final int cqhead=0x7f05003d;
        public static final int cques=0x7f05003e;
        public static final int errorMsg=0x7f050014;
        public static final int info=0x7f050043;
        public static final int login=0x7f05001a;
        public static final int loginWebView=0x7f05004b;
        public static final int menu_goto_springboard=0x7f05004c;
        public static final int menu_prefs=0x7f05004e;
        public static final int menu_rearrange=0x7f05004d;
        public static final int menu_show_hide_navbar=0x7f05004f;
        public static final int message=0x7f05000a;
        public static final int more_list=0x7f050010;
        public static final int more_list_title=0x7f05000f;
        public static final int more_title_bar=0x7f05000e;
        public static final int password=0x7f050005;
        public static final int passwordlbl=0x7f050016;
        public static final int processing=0x7f05001e;
        public static final int progessView=0x7f050044;
        public static final int progressBar1=0x7f05001d;
        public static final int progressLyt=0x7f05001c;
        public static final int pwprompt=0x7f050006;
        public static final int scrollView1=0x7f050021;
        public static final int server=0x7f050001;
        public static final int settings=0x7f05001f;
        public static final int shutdown=0x7f050009;
        public static final int sslMsg=0x7f050047;
        public static final int sslSettings=0x7f050048;
        public static final int sslTitle=0x7f050045;
        public static final int svrprompt=0x7f050002;
        public static final int tenantVal=0x7f050018;
        public static final int tenantid=0x7f050003;
        public static final int tenantlbl=0x7f050017;
        public static final int tidprompt=0x7f050004;
        public static final int txt_fingerprint=0x7f050037;
        public static final int txt_header_common_name=0x7f050023;
        public static final int txt_header_expiry=0x7f050035;
        public static final int txt_header_issued_on=0x7f050033;
        public static final int txt_header_issuer_org_unit=0x7f050030;
        public static final int txt_header_issuer_organization=0x7f05002e;
        public static final int txt_header_md5=0x7f05003a;
        public static final int txt_header_org_unit=0x7f050027;
        public static final int txt_header_organization=0x7f050025;
        public static final int txt_header_serial_number=0x7f050029;
        public static final int txt_header_sha1=0x7f050038;
        public static final int txt_issued_by=0x7f05002b;
        public static final int txt_issued_to=0x7f050022;
        public static final int txt_issuer_common_name=0x7f05002c;
        public static final int txt_validity=0x7f050032;
        public static final int txt_value_common_name=0x7f050024;
        public static final int txt_value_expiry=0x7f050036;
        public static final int txt_value_issued_on=0x7f050034;
        public static final int txt_value_issuer_common_name=0x7f05002d;
        public static final int txt_value_issuer_org_unit=0x7f050031;
        public static final int txt_value_issuer_organization=0x7f05002f;
        public static final int txt_value_md5=0x7f05003b;
        public static final int txt_value_org_unit=0x7f050028;
        public static final int txt_value_organization=0x7f050026;
        public static final int txt_value_serial_number=0x7f05002a;
        public static final int txt_value_sha1=0x7f050039;
        public static final int unprompt=0x7f050007;
        public static final int username=0x7f050008;
        public static final int usernamelbl=0x7f050015;
        public static final int view1=0x7f050046;
        public static final int view2=0x7f050020;
    }
    public static final class layout {
        public static final int adfmf_blank_activity=0x7f030000;
        public static final int adfmf_configsrvc_credentials=0x7f030001;
        public static final int adfmf_configsrvc_credentials_no_tenant=0x7f030002;
        public static final int adfmf_lifecycle_shutdown=0x7f030003;
        public static final int adfmf_log_text_view=0x7f030004;
        public static final int adfmf_login_page=0x7f030005;
        public static final int adfmf_main=0x7f030006;
        public static final int adfmf_more_page=0x7f030007;
        public static final int basicauth=0x7f030008;
        public static final int certificate=0x7f030009;
        public static final int challenge=0x7f03000a;
        public static final int information=0x7f03000b;
        public static final int progressview=0x7f03000c;
        public static final int sslwarning=0x7f03000d;
        public static final int webview=0x7f03000e;
    }
    public static final class menu {
        public static final int goto_springboard_menu=0x7f0a0000;
        public static final int more_rearrange_menu=0x7f0a0001;
        public static final int preferences_menu=0x7f0a0002;
        public static final int show_hide_navbar_menu=0x7f0a0003;
    }
    public static final class string {
        /**   Strings for the Config Service Connection Dialog  
         */
        public static final int Configuration=0x7f060000;
        public static final int Connect=0x7f060005;
        public static final int DefaultShutdownMessage=0x7f060007;
        public static final int Password=0x7f060003;
        public static final int Server=0x7f060004;
        /**   Strings for the Lifecycle Dialog  
         */
        public static final int Shutdown=0x7f060006;
        public static final int TenantID=0x7f060002;
        public static final int Username=0x7f060001;
        public static final int app_name=0x7f060044;
        public static final int authSuccess=0x7f060011;
        public static final int authfailed=0x7f060010;
        public static final int callbackexcep=0x7f060009;
        public static final int cancel=0x7f06000d;
        public static final int certificateNotAccepted=0x7f060042;
        public static final int chalgMissing=0x7f060017;
        public static final int challengeAns=0x7f060014;
        public static final int challengeHead=0x7f060012;
        public static final int challengeQues=0x7f060013;
        public static final int fingerprint=0x7f060034;
        public static final int initSSOAgentSuccess=0x7f06001d;
        public static final int internalError=0x7f06003e;
        public static final int invalidAppName=0x7f060039;
        public static final int invalidBasicUrl=0x7f060043;
        public static final int invalidConfig=0x7f060021;
        public static final int invalidServerType=0x7f060038;
        public static final int invalidServerUrl=0x7f06003a;
        public static final int invalidServiceDomain=0x7f06003b;
        public static final int login=0x7f06000c;
        public static final int md5_fp=0x7f060036;
        public static final int mssInitFailed=0x7f06001a;
        public static final int networkNotAvail=0x7f06003f;
        public static final int noAgentAvail=0x7f060022;
        public static final int noRpLoginUrl=0x7f06001e;
        public static final int noUserToken=0x7f060023;
        public static final int notConnectToServer=0x7f06003c;
        public static final int notParseResponse=0x7f06003d;
        public static final int oamms_app_name=0x7f060008;
        public static final int password=0x7f06000b;
        public static final int processing=0x7f060019;
        public static final int reqDenied=0x7f060037;
        public static final int reqFailed=0x7f060024;
        public static final int secProfileExcep=0x7f06000e;
        public static final int security_warning=0x7f06002f;
        public static final int serial_number=0x7f060033;
        public static final int serviceDomainNotSame=0x7f060020;
        public static final int servicenamenull=0x7f06001f;
        public static final int setupfailed=0x7f06000f;
        public static final int sha_fp=0x7f060035;
        public static final int sigNotValid=0x7f06001b;
        public static final int ssl_common_name=0x7f060028;
        public static final int ssl_continue=0x7f060030;
        public static final int ssl_expires_on=0x7f06002e;
        public static final int ssl_issued_by=0x7f06002b;
        public static final int ssl_issued_on=0x7f06002d;
        public static final int ssl_issued_to=0x7f060027;
        public static final int ssl_message=0x7f060032;
        public static final int ssl_organization=0x7f060029;
        public static final int ssl_organization_unit=0x7f06002a;
        public static final int ssl_security_certificate=0x7f060026;
        public static final int ssl_settingsheader=0x7f060025;
        public static final int ssl_validity=0x7f06002c;
        public static final int ssl_view_certificate=0x7f060031;
        public static final int ssoActivitymissing=0x7f06001c;
        public static final int submit=0x7f060015;
        public static final int tokenMissing=0x7f060018;
        public static final int tokensNoMatch=0x7f060041;
        public static final int unPwdMissing=0x7f060016;
        public static final int userCanceled=0x7f060040;
        public static final int username=0x7f06000a;
    }
    public static final class style {
        public static final int adfmf_splash_dialog=0x7f070000;
        public static final int adfmf_splash_dialog_full=0x7f070001;
    }
    public static final class xml {
        public static final int application_lifecycle_listeners=0x7f040000;
        public static final int plugins=0x7f040001;
    }
    public static final class styleable {
        /** Attributes that can be used with a AdfMFPreference.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #AdfMFPreference_editable com.company.GerenciarContatos:editable}</code></td><td></td></tr>
           <tr><td><code>{@link #AdfMFPreference_max com.company.GerenciarContatos:max}</code></td><td></td></tr>
           <tr><td><code>{@link #AdfMFPreference_min com.company.GerenciarContatos:min}</code></td><td></td></tr>
           <tr><td><code>{@link #AdfMFPreference_visible com.company.GerenciarContatos:visible}</code></td><td></td></tr>
           </table>
           @see #AdfMFPreference_editable
           @see #AdfMFPreference_max
           @see #AdfMFPreference_min
           @see #AdfMFPreference_visible
         */
        public static final int[] AdfMFPreference = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003
        };
        /**
          <p>This symbol is the offset where the {@link com.company.GerenciarContatos.R.attr#editable}
          attribute's value can be found in the {@link #AdfMFPreference} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:editable
        */
        public static final int AdfMFPreference_editable = 1;
        /**
          <p>This symbol is the offset where the {@link com.company.GerenciarContatos.R.attr#max}
          attribute's value can be found in the {@link #AdfMFPreference} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:max
        */
        public static final int AdfMFPreference_max = 3;
        /**
          <p>This symbol is the offset where the {@link com.company.GerenciarContatos.R.attr#min}
          attribute's value can be found in the {@link #AdfMFPreference} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:min
        */
        public static final int AdfMFPreference_min = 2;
        /**
          <p>This symbol is the offset where the {@link com.company.GerenciarContatos.R.attr#visible}
          attribute's value can be found in the {@link #AdfMFPreference} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:visible
        */
        public static final int AdfMFPreference_visible = 0;
    };
}
